# Machine Learning Workflow
Complete the steps below to complete the machine learning workflow for this classifier.

In [1]:
import nltk
nltk.download(['punkt', 'wordnet'])

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


True

In [2]:
import re
import pandas as pd
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

In [3]:
url_regex = 'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+'

def load_data():
    df = pd.read_csv('corporate_messaging.csv', encoding='latin-1')
    df = df[(df["category:confidence"] == 1) & (df['category'] != 'Exclude')]
    X = df.text.values
    y = df.category.values
    return X, y, df

def tokenize(text):
    detected_urls = re.findall(url_regex, text)
    for url in detected_urls:
        text = text.replace(url, "urlplaceholder")

    tokens = word_tokenize(text)
    lemmatizer = WordNetLemmatizer()

    clean_tokens = []
    for tok in tokens:
        clean_tok = lemmatizer.lemmatize(tok).lower().strip()
        clean_tokens.append(clean_tok)

    return clean_tokens

### Step 1: Load data and perform a train test split
Hint: you can use the [`train_test_split`](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html) method from sklearn.

In [40]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
import numpy as np

In [7]:
# load data
X, y, df = load_data()
X_train, X_test, y_train, y_test = train_test_split(X, y)

# perform train test split


### Step 2: Train classifier
* Fit and transform the training data with [`CountVectorizer`](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html). Hint: You can include your tokenize function in the `tokenizer` keyword argument!
* Fit and transform these word counts with [`TfidfTransformer`](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfTransformer.html).
* Fit or train a classifier to these tfidf values. Hint, you can use the [`RandomeForestClassifier`](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html) or other classifier of your choice.


In [44]:
# Instantiate transformers and classifier
vect = CountVectorizer(tokenizer = tokenize)
tfidf = TfidfTransformer()
X_train_counts = vect.fit_transform(X_train)
X_train_tfidf = tfidf.fit_transform(X_train_counts)
clf = RandomForestClassifier()
clf.fit(X_train_tfidf, y_train)

# Fit and/or transform each to the training data
# Hint: you can use the fit_transform method



# Fit or train the classifier



RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [45]:
X_test_counts = vect.transform(X_test)
X_test_tfidf = tfidf.transform(X_test_counts)
y_pred = clf.predict(X_test_tfidf)

In [47]:
labels = np.unique(y_pred)
confusion_mat = confusion_matrix(y_test, y_pred, labels = labels)
accuracy = (y_test == y_pred).mean()
print("Labels: ", labels)
print("Confusion Matrix: \n", confusion_mat)
print("Accuracy: ", accuracy)

Labels:  ['Action' 'Dialogue' 'Information']
Confusion Matrix: 
 [[ 94   2  25]
 [  1  28   1]
 [  9   2 439]]
Accuracy:  0.933444259567


### Step 3: Predict on test data
* Transform (no fitting) the test data with the same `CountVectorizer` and `TfidfTransformer`
* Predict labels on these tfidf values.

In [49]:
print("Akshara is greatt yeahhh and Shreyas is greatt yeahhhhhhhhhhhhhhh")

Akshara is greatt yeahhh and Shreyas is greatt yeahhhhhhhhhhhhhhh


In [ ]:
# Transform test data


# Predict test labels
y_pred = 

### Step 4: Display results
Use the variable `labels` to store all unique labels in the model's prediction. Then display a confusion matrix and accuracy score based on the model's predictions. 

Hint: you can use the [`confusion_matrix`](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.confusion_matrix.html) in sklearn to generate a confusion matrix.

Hint: to calculate the accuracy, you can use the number of correct predictions divided by the total number of predictions.

In [ ]:
labels = 
confusion_mat = 
accuracy = 

print("Labels:", labels)
print("Confusion Matrix:\n", confusion_mat)
print("Accuracy:", accuracy)

# Final Step: Refactor
Organize these steps into the following functions.

In [ ]:
def display_results():
    # insert step 4 here
    pass


def main():
    # insert steps 1 through 3 and the display_results() here
    pass

In [ ]:
# run program
main()